[package]
name = "memapi"
# major will always be 0 ngl
version = "0.11.0"
edition = "2021"
description = "A no_std-friendly memory allocation interface for raw buffers, with improved error reporting."
license = "MIT OR Apache-2.0"
repository = "https://github.com/afemboylol/memapi"
keywords = ["allocator", "no_std", "memory", "allocation"]
categories = ["no-std", "memory-management"]
exclude = ["/tests"]

[package.metadata.docs.rs]
features = ["full"]

[features]
nightly = []
std = []

metadata = ["nightly"]
clone_to_uninit = ["nightly"]
specialization = ["nightly"]

alloc_ext = []
resize_in_place = []

stats = []
owned = []

bytemuck = ["dep:bytemuck"]

jemalloc = ["dep:tikv-jemalloc-sys"]
jemalloc_in_place = ["jemalloc", "resize_in_place"]

mimalloc = ["dep:mimalloc-sys"]
mimalloc_in_place = ["mimalloc", "resize_in_place"]

full = [
    "specialization",
    "std",
    "metadata",
    "clone_to_uninit",
    "alloc_ext",
    "stats",
    "bytemuck",
    "jemalloc_in_place",
    "mimalloc_in_place"
]

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
bytemuck = { version = "1.23.0", optional = true }
tikv-jemalloc-sys = { version = "0.6.0", optional = true }
mimalloc-sys = { version = "0.1.6", optional = true }
