[package]
name = "memapi"
version = "0.8.0"
edition = "2024"
description = "A minimal, no_std-friendly memory allocation interface for raw buffers, with some error handling."
license = "MIT OR Apache-2.0"
repository = "https://github.com/barely-a-dev/memapi"
keywords = ["allocator", "no_std", "memory", "allocation"]
categories = ["no-std", "memory-management"]
exclude = ["/tests"]

[package.metadata.docs.rs]
features = ["alloc_ext", "std", "metadata", "clone_to_uninit", "stats"]

[features]
nightly = []
std = []

metadata = ["nightly"]
clone_to_uninit = ["nightly"]

alloc_ext = ["metadata"]
resize_in_place = []

stats = []

[[test]]
name = "test"
path = "tests/test.rs"
