[package]
name = "memapi"
# major will probably always be 0
version = "0.13.2"
edition = "2018"
readme = "README.md"
rust-version = "1.40.0"
description = "A no_std-friendly memory allocation interface for raw buffers, with improved error reporting."
license = "MIT OR Apache-2.0"
repository = "https://github.com/afemboylol/memapi"
keywords = ["allocator", "no_std", "memory", "allocation"]
categories = ["no-std", "memory-management"]
exclude = ["/tests", "/bin", "testall.py", "src/expanded"]

[package.metadata.docs.rs]
features = ["full"]

[features]
nightly = []
std = []

metadata = ["nightly"]
sized_hierarchy = ["nightly"]
clone_to_uninit = ["nightly"]
specialization = ["nightly"]

all_nightly = ["metadata", "sized_hierarchy", "clone_to_uninit", "specialization"]

alloc_ext = []
alloc_slice = ["alloc_ext"]
resize_in_place = []

stats = []
owned = ["metadata"]

drop_for_owned = ["owned"]
zero_drop_for_owned = ["owned"]

jemalloc = ["dep:tikv-jemalloc-sys", "cty"]
jemalloc_in_place = ["jemalloc", "resize_in_place"]

mimalloc = ["dep:libmimalloc-sys"]
mimalloc_in_place = ["mimalloc", "resize_in_place"]

full_no_std_no_nightly = [
    "alloc_slice",
    "stats",
    "jemalloc_in_place",
    "mimalloc_in_place",
]

full_no_nightly = [
    "std",

    "full_no_std_no_nightly"
]

full_no_std = [
    "all_nightly",

    "full_no_std_no_nightly",
]

full = [
    "full_no_nightly",
    "full_no_std"
]

default = ["full"]

[[test]]
name = "test"
path = "tests/test.rs"

[[test]]
name = "dangerous"
path = "tests/potential_ub.rs"

[dependencies]
tikv-jemalloc-sys = { version = "0.6.0", optional = true }
cty = { version = "0.2.2", optional = true }
libmimalloc-sys = { version = "0.1.43", optional = true, features = ["extended"] }
