[package]
name = "memapi"
# major will probably always be 0
edition = "2021"
rust-version = "1.56.0"
version = "0.13.2"
readme = "README.md"
description = "A no_std-friendly memory allocation interface for raw buffers, with improved error reporting."
license = "MIT OR Apache-2.0"
repository = "https://github.com/afemboylol/memapi"
keywords = ["allocator", "no_std", "memory", "allocation"]
categories = ["no-std", "memory-management"]
exclude = ["/tests", "/bin", "testall.py", "src/expanded"]

[package.metadata.docs.rs]
features = ["full"]

[features]
nightly = []
std = []

metadata = ["nightly"]
sized_hierarchy = ["nightly"]
clone_to_uninit = ["nightly"]
specialization = ["nightly"]

alloc_ext = []
alloc_slice = ["alloc_ext"]
resize_in_place = []

stats = []
owned = ["metadata"]

drop_for_owned = ["owned"]
zero_drop_for_owned = ["owned"]

jemalloc = ["dep:tikv-jemalloc-sys"]
jemalloc_in_place = ["jemalloc", "resize_in_place"]

mimalloc = ["dep:libmimalloc-sys"]
mimalloc_in_place = ["mimalloc", "resize_in_place"]

full_no_std_no_nightly = [
    "alloc_slice",
    "stats",
    "jemalloc_in_place",
    "mimalloc_in_place",
]

full_no_nightly = [
    "std",

    "full_no_std_no_nightly"
]

full_no_std = [
    "metadata",
    "sized_hierarchy",
    "clone_to_uninit",
    "owned",

    "full_no_std_no_nightly",
]

full = [
    "full_no_nightly",
    "full_no_std"
]

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
tikv-jemalloc-sys = { version = "0.6.0", optional = true }
libmimalloc-sys = { version = "0.1.43", optional = true, features = ["extended"] }
