[package]
name = "memapi"
# major will always be 0 ngl
version = "0.12.4"
edition = "2021"
description = "A no_std-friendly memory allocation interface for raw buffers, with improved error reporting."
license = "MIT OR Apache-2.0"
repository = "https://github.com/afemboylol/memapi"
keywords = ["allocator", "no_std", "memory", "allocation"]
categories = ["no-std", "memory-management"]
exclude = ["/tests", "/bin", "testall.py"]

[package.metadata.docs.rs]
features = ["full"]

[features]
nightly = []
std = []

metadata = ["nightly"]
clone_to_uninit = ["nightly"]
specialization = ["nightly"]

alloc_ext = []
alloc_slice = ["alloc_ext"]
resize_in_place = []

stats = []
owned = []

jemalloc = ["dep:tikv-jemalloc-sys"]
jemalloc_in_place = ["jemalloc", "resize_in_place"]

mimalloc = ["dep:libmimalloc-sys"]
mimalloc_in_place = ["mimalloc", "resize_in_place"]

full = [
    "specialization",
    "std",
    "metadata",
    "clone_to_uninit",
    "alloc_slice",
    "stats",
    "owned",
    "jemalloc_in_place",
    "mimalloc_in_place",
]

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
tikv-jemalloc-sys = { version = "0.6.0", optional = true }
libmimalloc-sys = { version = "0.1.43", optional = true, features = ["extended"] }
